// Generated by scripts/dictionaries/generate_place_names.py.
// Source of truth: data/place-names.json (corpus 2026-09-01).
// Do not edit this file directly.

package io.github.supermonster003.autojs6.plugin.pinyin

internal object PlaceNameReadings {
    val ALL: Map<String, List<String>> = linkedMapOf(
        "六安" to listOf("lù", "ān"),
        "丽水" to listOf("lí", "shuǐ"),
        "乐清" to listOf("yuè", "qīng"),
        "歙县" to listOf("shè", "xiàn"),
        "蚌埠" to listOf("bèng", "bù"),
        "盱眙" to listOf("xū", "yí"),
        "栟茶" to listOf("bēn", "chá"),
        "巴彦淖尔" to listOf("bā", "yàn", "nào", "ěr"),
        "蔚县" to listOf("yù", "xiàn"),
        "黄陂" to listOf("huáng", "pí"),
        "监利" to listOf("jiàn", "lì"),
        "浚县" to listOf("xùn", "xiàn"),
        "铅山" to listOf("yán", "shān"),
        "台州" to listOf("tāi", "zhōu"),
        "乐亭" to listOf("lào", "tíng"),
    )
}
