#!/usr/bin/env python3
"""Validate the curated place-name corpus and generate runtime/docs artifacts."""

from __future__ import annotations

import argparse
import json
import sys
import unicodedata
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_INPUT = REPO_ROOT / "data" / "place-names.json"
KOTLIN_OUTPUT = (
    REPO_ROOT
    / "app"
    / "src"
    / "main"
    / "java"
    / "io"
    / "github"
    / "supermonster003"
    / "autojs6"
    / "plugin"
    / "pinyin"
    / "PlaceNameReadings.kt"
)
MARKDOWN_OUTPUT = REPO_ROOT / "docs" / "dictionaries" / "place-names.md"

PINYIN_CHARACTERS = frozenset(
    "abcdefghijklmnopqrstuvwxyz"
    "üāáǎàēéěèīíǐìōóǒòūúǔùǖǘǚǜńňǹḿ"
)


class CorpusError(ValueError):
    """Raised when the canonical corpus does not satisfy its schema."""


def load_corpus(path: Path = DEFAULT_INPUT) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as source:
        corpus = json.load(source)
    validate_corpus(corpus)
    return corpus


def validate_corpus(corpus: dict[str, Any]) -> None:
    if corpus.get("schemaVersion") != 1:
        raise CorpusError("schemaVersion must be 1")
    if not isinstance(corpus.get("corpusVersion"), str) or not corpus["corpusVersion"]:
        raise CorpusError("corpusVersion must be a non-empty string")

    sources = corpus.get("sources")
    if not isinstance(sources, dict) or not sources:
        raise CorpusError("sources must be a non-empty object")
    for source_id, source in sources.items():
        if not isinstance(source_id, str) or not source_id:
            raise CorpusError("source IDs must be non-empty strings")
        if not isinstance(source, dict):
            raise CorpusError(f"source {source_id!r} must be an object")
        for field in ("title", "publisher", "reviewedOn"):
            if not isinstance(source.get(field), str) or not source[field]:
                raise CorpusError(f"source {source_id!r} has no valid {field}")
        url = source.get("url")
        if not isinstance(url, str) or not url.startswith("https://"):
            raise CorpusError(f"source {source_id!r} must use an HTTPS URL")

    entries = corpus.get("entries")
    if not isinstance(entries, list) or not entries:
        raise CorpusError("entries must be a non-empty array")

    seen_names: set[str] = set()
    for index, entry in enumerate(entries):
        if not isinstance(entry, dict):
            raise CorpusError(f"entry {index} must be an object")
        name = entry.get("name")
        if not isinstance(name, str) or len(name) < 2 or name.strip() != name:
            raise CorpusError(f"entry {index} has an invalid name")
        if name != unicodedata.normalize("NFC", name):
            raise CorpusError(f"place name {name!r} must use NFC normalization")
        if name in seen_names:
            raise CorpusError(f"duplicate place name: {name}")
        seen_names.add(name)

        pinyin = entry.get("pinyin")
        if not isinstance(pinyin, list) or len(pinyin) != len(name):
            raise CorpusError(f"place name {name!r} must have one syllable per character")
        for syllable in pinyin:
            if (
                not isinstance(syllable, str)
                or not syllable
                or syllable != unicodedata.normalize("NFC", syllable)
                or any(character not in PINYIN_CHARACTERS for character in syllable)
            ):
                raise CorpusError(f"place name {name!r} has invalid syllable {syllable!r}")

        source_ids = entry.get("sourceIds")
        if not isinstance(source_ids, list) or not source_ids:
            raise CorpusError(f"place name {name!r} must cite at least one source")
        unknown_sources = [source_id for source_id in source_ids if source_id not in sources]
        if unknown_sources:
            raise CorpusError(f"place name {name!r} cites unknown sources: {unknown_sources}")
        if len(source_ids) != len(set(source_ids)):
            raise CorpusError(f"place name {name!r} cites a source more than once")


def kotlin_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_kotlin(corpus: dict[str, Any]) -> str:
    rows = []
    for entry in corpus["entries"]:
        syllables = ", ".join(kotlin_string(item) for item in entry["pinyin"])
        rows.append(f"        {kotlin_string(entry['name'])} to listOf({syllables}),")
    body = "\n".join(rows)
    return f"""// Generated by scripts/dictionaries/generate_place_names.py.
// Source of truth: data/place-names.json (corpus {corpus['corpusVersion']}).
// Do not edit this file directly.

package io.github.supermonster003.autojs6.plugin.pinyin

internal object PlaceNameReadings {{
    val ALL: Map<String, List<String>> = linkedMapOf(
{body}
    )
}}
"""


def render_markdown(corpus: dict[str, Any]) -> str:
    sources = corpus["sources"]
    lines = [
        "<!-- Generated by scripts/dictionaries/generate_place_names.py; do not edit directly. -->",
        "",
        "# PLACE_NAME 精选地名读音语料",
        "",
        f"- 语料版本: `{corpus['corpusVersion']}`",
        f"- 条目数: `{len(corpus['entries'])}`",
        "",
        "这是一份刻意保持小规模、逐条人工复核的差异化语料，解决常见逐字首选读音不适用于地名的问题；它不是全国标准地名全量库，也不承诺覆盖任意行政区或自然地理实体。运行时在 `PLACE_NAME` 模式下采用最长匹配，未命中的文本回退到 `NORMAL` 转换。`SURNAME` 与 `PLACE_NAME` 是互斥模式，不叠加优先级。",
        "",
        "规范性背景参见教育部发布的[《中文地名汉语拼音字母拼写规则（汉语地名部分）》](https://www.moe.gov.cn/ewebeditor/uploadfile/2015/01/12/20150112161950748.pdf)：多音字、方言字的读音依据审定音或当地政府确认的读音。当前条目的直接读音证据列于下表的政府网站来源。",
        "",
        "| 地名 | 固定读音 | 复核来源 |",
        "|---|---|---|",
    ]
    for entry in corpus["entries"]:
        citations = "；".join(
            f"[{sources[source_id]['publisher']}]({sources[source_id]['url']})"
            for source_id in entry["sourceIds"]
        )
        lines.append(f"| {entry['name']} | `{' '.join(entry['pinyin'])}` | {citations} |")

    lines.extend(
        [
            "",
            "## 维护流程",
            "",
            "1. 仅在找到可公开复核的政府/权威来源后编辑 `data/place-names.json`，每个汉字写一个带调拼音音节。",
            "2. 运行 `py scripts/dictionaries/generate_place_names.py` 生成运行时 Kotlin 映射与本文档。",
            "3. 运行 `py scripts/dictionaries/generate_place_names.py --check`、JVM 测试和 Binder instrumentation 测试。",
            "4. 在 PR 中人工审阅语料、来源与输出差分；生成脚本不会联网，也不会自动吸收上游变化。",
            "",
        ]
    )
    return "\n".join(lines)


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        actual = path.read_text(encoding="utf-8") if path.exists() else None
        if actual != content:
            print(f"out of date: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"generated: {path.relative_to(REPO_ROOT)}")
    return True


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated outputs differ")
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT, help="canonical corpus JSON")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        corpus = load_corpus(args.input)
    except (OSError, json.JSONDecodeError, CorpusError) as error:
        print(f"place-name corpus error: {error}", file=sys.stderr)
        return 1
    current = [
        write_or_check(KOTLIN_OUTPUT, render_kotlin(corpus), args.check),
        write_or_check(MARKDOWN_OUTPUT, render_markdown(corpus), args.check),
    ]
    return 0 if all(current) else 1


if __name__ == "__main__":
    raise SystemExit(main())
